name: Metrics

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          user: penrodlol
          filename: assets/metrics.*
          base: header, activity, community, repositories, metadata
          committer_message: '📈 Metrics'
          config_timezone: America/New_York
          config_output: json

          # Lines
          plugin_lines: yes
